# -*- coding: utf-8 -*-
"""08102024.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/15592dkeXN_JBF71bwpzs_jngkaiZrJTK
"""

print("Ramesh")

import numpy as np

l1=[1,2,3]
a=np.array(l1)
a

print(a)

b=np.array([2,4,6,8])
print(b)

b

c=np.array([[1,2,3],[3,5,7],[3,8,9]])
print(c)

c

print(c[0,0])

print(np.__version__)