# -*- coding: utf-8 -*-
"""09102024.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1MFV8qHuOHu7gpXnMN34mPE5Ec5SSQsW8
"""

import numpy as np

a=np.array([[1,2,3,4],[5,6,7,8],[9,10,11,12]])
b=np.array([1,2,3,4])
print(a[0])
print(b[0])

print(a)
print(b)

print(a[3])
print(b[3])

print(a[2])

# access the element of array

a[0][2]

a[2][3]

# one time take only one cell easy understanding capability

"""**nothing here just practice we can know**"""

print(a[2],end=" ")
print(b[0])

a=np.linspace(0,1,10)
print(a)

a=np.linspace(0,1,11)
print(a)

a=np.linspace(0,9,3)
print(a)

a=np.linspace(1,9,4)
print(a)

"""samantaar series print    a=np.linspace(0,9,3)
print(a)
"""

a=np.linspace(10,25,6)
print(a)

a=np.zeros(3)
print(a)

a=np.zeros(3,4)
print(a)

a=np.zeros((3,4))
print(a)

a=np.zeros(((3,4,2)))
print(a)

a=np.zeros((((2,3,4,2))))
print(a)

a=np.ones(4)
print(a)

a=np.ones((3,4))
print(a)